name: BukkitJail
main: fr.skyost.jail.BukkitJail
description: Simple jail plugin.
version: 0.3
author: Skyost
website: http://www.skyost.eu/
commands:
 jail:
  description: Jail a player.
  usage: Simply type /jail <player> [reason] [time] for jailing him.
  permission: bukkitjail.jail
 unjail:
  aliases: release
  description: Release a player.
  usage: Simply type /unjail <player> (or /release <player>) for releasing him.
  permission: bukkitjail.release
 setjail:
  description: Set the jail at your current position.
  usage: Simply type /setjail for setting the jail at your current location.
  permission: bukkitjail.setjail
permissions:
 bukkitjail.jail:
  default: op
  description: Allow you to jailing a player.
 bukkitjail.release:
  default: op
  description: Allow you to releasing a player.
 bukkitjail.setjail:
  default: op
  description: Allow you to setting the jail location.
